//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.Controllers.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ab81e1b26160402e86c134cc4bc53f55 {
            get {
                return ResourceManager.GetString("ab81e1b26160402e86c134cc4bc53f55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add material.
        /// </summary>
        public static string AddMaterial {
            get {
                return ResourceManager.GetString("AddMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new image..
        /// </summary>
        public static string AddNewImage {
            get {
                return ResourceManager.GetString("AddNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new application for participation in your course..
        /// </summary>
        public static string b3f1a68fbceb498497a5c21b6170baf5 {
            get {
                return ResourceManager.GetString("b3f1a68fbceb498497a5c21b6170baf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were adopted in the course.
        /// </summary>
        public static string b74c4efaccfa44f3ba51d834c257ae16 {
            get {
                return ResourceManager.GetString("b74c4efaccfa44f3ba51d834c257ae16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to course..
        /// </summary>
        public static string bb81ab8cfb1745708af8ab41b4b74368 {
            get {
                return ResourceManager.GetString("bb81ab8cfb1745708af8ab41b4b74368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam for level.
        /// </summary>
        public static string c999d7d108874d94abbc95ffb2118a99 {
            get {
                return ResourceManager.GetString("c999d7d108874d94abbc95ffb2118a99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully did you level .
        /// </summary>
        public static string ca779cae33834c0fbd4491b45e066343 {
            get {
                return ResourceManager.GetString("ca779cae33834c0fbd4491b45e066343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password by clicking here.
        /// </summary>
        public static string ChangeYourPassHere {
            get {
                return ResourceManager.GetString("ChangeYourPassHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one student!.
        /// </summary>
        public static string ChooseOneStudent {
            get {
                return ResourceManager.GetString("ChooseOneStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from course..
        /// </summary>
        public static string d1b83438729e43b886f48920a0478a0f {
            get {
                return ResourceManager.GetString("d1b83438729e43b886f48920a0478a0f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new test for solving for level.
        /// </summary>
        public static string d3357bfa357649c2859fd8041a445ef4 {
            get {
                return ResourceManager.GetString("d3357bfa357649c2859fd8041a445ef4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one new mark..
        /// </summary>
        public static string d482501cd64540118d525ea74747a692 {
            get {
                return ResourceManager.GetString("d482501cd64540118d525ea74747a692", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new video.
        /// </summary>
        public static string e35211cee5764713846c0366b4fb97f41 {
            get {
                return ResourceManager.GetString("e35211cee5764713846c0366b4fb97f41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is occupied..
        /// </summary>
        public static string EmailOccupied {
            get {
                return ResourceManager.GetString("EmailOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new test for solving.
        /// </summary>
        public static string f797056e86c24aaa9d603a92366d2526 {
            get {
                return ResourceManager.GetString("f797056e86c24aaa9d603a92366d2526", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new video..
        /// </summary>
        public static string f8d83880ec11490284d74705e43ecc49 {
            get {
                return ResourceManager.GetString("f8d83880ec11490284d74705e43ecc49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field About me contains dangerous words..
        /// </summary>
        public static string FieldAboutMeDanger {
            get {
                return ResourceManager.GetString("FieldAboutMeDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Answer contains dangerous words..
        /// </summary>
        public static string FieldAnsDanger {
            get {
                return ResourceManager.GetString("FieldAnsDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Answer is required..
        /// </summary>
        public static string FieldAnsRequired {
            get {
                return ResourceManager.GetString("FieldAnsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Description contains dangerous words!.
        /// </summary>
        public static string FieldDescriptionDanger {
            get {
                return ResourceManager.GetString("FieldDescriptionDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Question is required..
        /// </summary>
        public static string FieldQRequired {
            get {
                return ResourceManager.GetString("FieldQRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required !.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Question contains dangerous words..
        /// </summary>
        public static string FiledQDanger {
            get {
                return ResourceManager.GetString("FiledQDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string HaveOneDigit {
            get {
                return ResourceManager.GetString("HaveOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not selected test for level!.
        /// </summary>
        public static string NoChooseTest {
            get {
                return ResourceManager.GetString("NoChooseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email does not exist..
        /// </summary>
        public static string NoEmailExist {
            get {
                return ResourceManager.GetString("NoEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user !.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one correct answer..
        /// </summary>
        public static string OneCorrectAns {
            get {
                return ResourceManager.GetString("OneCorrectAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred, please try again..
        /// </summary>
        public static string ProblemTryAgain {
            get {
                return ResourceManager.GetString("ProblemTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new test for checking..
        /// </summary>
        public static string q27e30c9e92b4b11bb5a420f7a98e29d {
            get {
                return ResourceManager.GetString("q27e30c9e92b4b11bb5a420f7a98e29d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of field Points must be number.
        /// </summary>
        public static string ShouldBeNum {
            get {
                return ResourceManager.GetString("ShouldBeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone use this question now !.
        /// </summary>
        public static string SomeoneUserThisQ {
            get {
                return ResourceManager.GetString("SomeoneUserThisQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone use this test. Please try again later!.
        /// </summary>
        public static string SomeoneUserThisTest {
            get {
                return ResourceManager.GetString("SomeoneUserThisTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone use this test now and you can not add a question!.
        /// </summary>
        public static string SomeoneUserThisTestNoQ {
            get {
                return ResourceManager.GetString("SomeoneUserThisTestNoQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is used and can not be deleted!.
        /// </summary>
        public static string SomeoneUseThisCourse {
            get {
                return ResourceManager.GetString("SomeoneUseThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone use this topic. Please try again later!.
        /// </summary>
        public static string SomeoneUseThisTopic {
            get {
                return ResourceManager.GetString("SomeoneUseThisTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your password.
        /// </summary>
        public static string SuccessChangePass {
            get {
                return ResourceManager.GetString("SuccessChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string t4c66efaa35043beaaeb5f7e7c6a1ed1 {
            get {
                return ResourceManager.GetString("t4c66efaa35043beaaeb5f7e7c6a1ed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPass {
            get {
                return ResourceManager.GetString("WrongPass", resourceCulture);
            }
        }
    }
}
