//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.ViewModels.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPass {
            get {
                return ResourceManager.GetString("CurrentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Current password is required.
        /// </summary>
        public static string FieldCurentPassRequired {
            get {
                return ResourceManager.GetString("FieldCurentPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email is required..
        /// </summary>
        public static string FieldEmailRequired {
            get {
                return ResourceManager.GetString("FieldEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field First Name is required..
        /// </summary>
        public static string FieldFirstNameRequired {
            get {
                return ResourceManager.GetString("FieldFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Last Name is required..
        /// </summary>
        public static string FieldLastNameRequired {
            get {
                return ResourceManager.GetString("FieldLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required.
        /// </summary>
        public static string FieldNameRequired {
            get {
                return ResourceManager.GetString("FieldNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field New password is required.
        /// </summary>
        public static string FieldNewPassRequired {
            get {
                return ResourceManager.GetString("FieldNewPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Password is required..
        /// </summary>
        public static string FieldPassRequired {
            get {
                return ResourceManager.GetString("FieldPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Second Name is required..
        /// </summary>
        public static string FieldSecondNameRequired {
            get {
                return ResourceManager.GetString("FieldSecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not correct..
        /// </summary>
        public static string NotCorrectEmail {
            get {
                return ResourceManager.GetString("NotCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PassSDontMach {
            get {
                return ResourceManager.GetString("PassSDontMach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should be at least 6 characters long.
        /// </summary>
        public static string ShoudBeAtLeast {
            get {
                return ResourceManager.GetString("ShoudBeAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
    }
}
