//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aiken {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aiken() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.Views.Aiken", typeof(Aiken).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiken format allows for easy creation of open questions with multiple answers..
        /// </summary>
        public static string Aiken1 {
            get {
                return ResourceManager.GetString("Aiken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A) Is this the correct answer ?.
        /// </summary>
        public static string Aiken10 {
            get {
                return ResourceManager.GetString("Aiken10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B) It may be this..
        /// </summary>
        public static string Aiken11 {
            get {
                return ResourceManager.GetString("Aiken11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C) It is probably this..
        /// </summary>
        public static string Aiken12 {
            get {
                return ResourceManager.GetString("Aiken12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D) You need to is this..
        /// </summary>
        public static string Aiken13 {
            get {
                return ResourceManager.GetString("Aiken13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSWER: А.
        /// </summary>
        public static string Aiken14 {
            get {
                return ResourceManager.GetString("Aiken14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both examples will make the same question..
        /// </summary>
        public static string Aiken15 {
            get {
                return ResourceManager.GetString("Aiken15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some examples:.
        /// </summary>
        public static string Aiken2 {
            get {
                return ResourceManager.GetString("Aiken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which answer is correct?.
        /// </summary>
        public static string Aiken3 {
            get {
                return ResourceManager.GetString("Aiken3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Is this the correct answer ?.
        /// </summary>
        public static string Aiken4 {
            get {
                return ResourceManager.GetString("Aiken4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. It may be this..
        /// </summary>
        public static string Aiken5 {
            get {
                return ResourceManager.GetString("Aiken5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. It is probably this..
        /// </summary>
        public static string Aiken6 {
            get {
                return ResourceManager.GetString("Aiken6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D. You need to is this..
        /// </summary>
        public static string Aiken7 {
            get {
                return ResourceManager.GetString("Aiken7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSWER: D.
        /// </summary>
        public static string Aiken8 {
            get {
                return ResourceManager.GetString("Aiken8", resourceCulture);
            }
        }
    }
}
