//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Course {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Course() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.Views.Course", typeof(Course).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add participant.
        /// </summary>
        public static string AddParticipant {
            get {
                return ResourceManager.GetString("AddParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to courses.
        /// </summary>
        public static string BackToCourses {
            get {
                return ResourceManager.GetString("BackToCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a course.
        /// </summary>
        public static string ChooseCourse {
            get {
                return ResourceManager.GetString("ChooseCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a level.
        /// </summary>
        public static string ChooseLevel {
            get {
                return ResourceManager.GetString("ChooseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete course.
        /// </summary>
        public static string CompleteCourse {
            get {
                return ResourceManager.GetString("CompleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed courses.
        /// </summary>
        public static string CompletedCourses {
            get {
                return ResourceManager.GetString("CompletedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed levels in courses.
        /// </summary>
        public static string CompletedLevels {
            get {
                return ResourceManager.GetString("CompletedLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlling examinations.
        /// </summary>
        public static string ContrExam {
            get {
                return ResourceManager.GetString("ContrExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseN {
            get {
                return ResourceManager.GetString("CourseN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new course.
        /// </summary>
        public static string CreateNewCourse {
            get {
                return ResourceManager.GetString("CreateNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current courses.
        /// </summary>
        public static string CurrentCourses {
            get {
                return ResourceManager.GetString("CurrentCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit course.
        /// </summary>
        public static string EditCourse {
            get {
                return ResourceManager.GetString("EditCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination.
        /// </summary>
        public static string Examination {
            get {
                return ResourceManager.GetString("Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination for level.
        /// </summary>
        public static string ExaminationForLevel {
            get {
                return ResourceManager.GetString("ExaminationForLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose course.
        /// </summary>
        public static string PleaseChooseCourse {
            get {
                return ResourceManager.GetString("PleaseChooseCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove course.
        /// </summary>
        public static string RemoveCourse {
            get {
                return ResourceManager.GetString("RemoveCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications for participation in the courses.
        /// </summary>
        public static string RequestForАpp {
            get {
                return ResourceManager.GetString("RequestForАpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for courses.
        /// </summary>
        public static string RequestsForCourse {
            get {
                return ResourceManager.GetString("RequestsForCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your courses.
        /// </summary>
        public static string YourCourses {
            get {
                return ResourceManager.GetString("YourCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current courses.
        /// </summary>
        public static string YourCurrentCourses {
            get {
                return ResourceManager.GetString("YourCurrentCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your levels in courses.
        /// </summary>
        public static string YourLevels {
            get {
                return ResourceManager.GetString("YourLevels", resourceCulture);
            }
        }
    }
}
