//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Question {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Question() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.Views.Question", typeof(Question).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string AddAnswer {
            get {
                return ResourceManager.GetString("AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add close question.
        /// </summary>
        public static string AddCloseQ {
            get {
                return ResourceManager.GetString("AddCloseQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an open question.
        /// </summary>
        public static string AddOpenQ {
            get {
                return ResourceManager.GetString("AddOpenQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a question.
        /// </summary>
        public static string AddQ {
            get {
                return ResourceManager.GetString("AddQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to questions.
        /// </summary>
        public static string BackToQs {
            get {
                return ResourceManager.GetString("BackToQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose questions.
        /// </summary>
        public static string ChooseQs {
            get {
                return ResourceManager.GetString("ChooseQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close questions.
        /// </summary>
        public static string CloseQuestions {
            get {
                return ResourceManager.GetString("CloseQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully uploaded.
        /// </summary>
        public static string CompleteUpload {
            get {
                return ResourceManager.GetString("CompleteUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers.
        /// </summary>
        public static string CorrectAnss {
            get {
                return ResourceManager.GetString("CorrectAnss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete answer.
        /// </summary>
        public static string DeleteAnswer {
            get {
                return ResourceManager.GetString("DeleteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the question.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of questions.
        /// </summary>
        public static string NumOfQs {
            get {
                return ResourceManager.GetString("NumOfQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open questions.
        /// </summary>
        public static string OpenQuestions {
            get {
                return ResourceManager.GetString("OpenQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions.
        /// </summary>
        public static string QuestionsA {
            get {
                return ResourceManager.GetString("QuestionsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To questions.
        /// </summary>
        public static string ToQuestions {
            get {
                return ResourceManager.GetString("ToQuestions", resourceCulture);
            }
        }
    }
}
