//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTraining.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTraining.Resources.Views.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a generated test.
        /// </summary>
        public static string AddGenTest {
            get {
                return ResourceManager.GetString("AddGenTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a simple test.
        /// </summary>
        public static string AddSimpleTest {
            get {
                return ResourceManager.GetString("AddSimpleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check by the leader.
        /// </summary>
        public static string CheckedLeader {
            get {
                return ResourceManager.GetString("CheckedLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked by the leader.
        /// </summary>
        public static string CheckedLeader1 {
            get {
                return ResourceManager.GetString("CheckedLeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check by the system.
        /// </summary>
        public static string CheckedSys {
            get {
                return ResourceManager.GetString("CheckedSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked by the system.
        /// </summary>
        public static string CheckedSys1 {
            get {
                return ResourceManager.GetString("CheckedSys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose test.
        /// </summary>
        public static string ChooseTest {
            get {
                return ResourceManager.GetString("ChooseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way To Go.
        ///     You can see the test after being checked by the head..
        /// </summary>
        public static string ComlManTestDes {
            get {
                return ResourceManager.GetString("ComlManTestDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way To Go. You can go passed the level.
        /// </summary>
        public static string CompleteTest {
            get {
                return ResourceManager.GetString("CompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a generated test.
        /// </summary>
        public static string CreateGenTest {
            get {
                return ResourceManager.GetString("CreateGenTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a simple test.
        /// </summary>
        public static string CreateSimpleTest {
            get {
                return ResourceManager.GetString("CreateSimpleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not go passed the level.
        /// </summary>
        public static string NoCompleteTest {
            get {
                return ResourceManager.GetString("NoCompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose test for level.
        /// </summary>
        public static string PleaseChooseTestForLevel {
            get {
                return ResourceManager.GetString("PleaseChooseTestForLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the test.
        /// </summary>
        public static string SendTest {
            get {
                return ResourceManager.GetString("SendTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved tests.
        /// </summary>
        public static string SolvedTests {
            get {
                return ResourceManager.GetString("SolvedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students who have not choose the test.
        /// </summary>
        public static string StudentsNoSolve {
            get {
                return ResourceManager.GetString("StudentsNoSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students who choose the test.
        /// </summary>
        public static string StudentsSolve {
            get {
                return ResourceManager.GetString("StudentsSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests verified by the leader.
        /// </summary>
        public static string TestCheckByLeader {
            get {
                return ResourceManager.GetString("TestCheckByLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests checked by the system.
        /// </summary>
        public static string TestCheckBySystem {
            get {
                return ResourceManager.GetString("TestCheckBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests for levels.
        /// </summary>
        public static string TestForLevels {
            get {
                return ResourceManager.GetString("TestForLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestN {
            get {
                return ResourceManager.GetString("TestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests for checking ( levels).
        /// </summary>
        public static string TestsForCheckLevels {
            get {
                return ResourceManager.GetString("TestsForCheckLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests for checking.
        /// </summary>
        public static string TestsForCheking {
            get {
                return ResourceManager.GetString("TestsForCheking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests for solving.
        /// </summary>
        public static string TestsForSolv {
            get {
                return ResourceManager.GetString("TestsForSolv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for solving ( levels ).
        /// </summary>
        public static string TestsForSolvLevel {
            get {
                return ResourceManager.GetString("TestsForSolvLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type tests.
        /// </summary>
        public static string TypeTests {
            get {
                return ResourceManager.GetString("TypeTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tests.
        /// </summary>
        public static string YourTests {
            get {
                return ResourceManager.GetString("YourTests", resourceCulture);
            }
        }
    }
}
